name: polygonal_draft
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'
  
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  formz: ^0.4.1
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  logger: ^2.1.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1
  svg_path_parser: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.3.11
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.9
  
flutter:
  assets:
    - assets/
    - assets/svg/
  uses-material-design: true
